### ISSUE TITLE
Code implementation question: no rotation predicted?

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [SkyworkAI/Gamba#7]
Dear authors, during reading the code implementaion, I found code related to rotation parameter of 3D GS seems to be constant.

In particular, the following defines the "rot" as fixed parameters.
https://github.com/SkyworkAI/Gamba/blob/995d8d7ef7054213b457b71d3f9a060dd027be5c/core/gamba_models.py#L126

And they are kept constant during prediction according to 
https://github.com/SkyworkAI/Gamba/blob/995d8d7ef7054213b457b71d3f9a060dd027be5c/core/gamba_models.py#L216-L218

Did I miss something that leads to misunderstanding? I appreciate for your warm reply.

**Comment by florinshen** [comment]
Exactly, the rotation is fixed in Gamba's prediction. The reason for this setting is that the rotation of GS predicted from single view cannot be robust. When we try to learn rotation with other attributes of GS, the convergence in training would be much slower, and the evaluation PSNR in training phase was degraded. Such that we choose to directly fix the rotation in prediction phase.
